from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_programs_download(object):
    def setupUi(self, programs_download):
        programs_download.setObjectName("programs_download")
        programs_download.resize(290, 90)
        programs_download.setMinimumSize(QtCore.QSize(290, 90))
        programs_download.setMaximumSize(QtCore.QSize(290, 90))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        programs_download.setFont(font)
        self.widget = QtWidgets.QWidget(parent=programs_download)
        self.widget.setGeometry(QtCore.QRect(10, 10, 268, 71))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.windows_button = QtWidgets.QPushButton(parent=self.widget)
        self.windows_button.setObjectName("windows_button")
        self.horizontalLayout.addWidget(self.windows_button)
        self.linux_button = QtWidgets.QPushButton(parent=self.widget)
        self.linux_button.setObjectName("linux_button")
        self.horizontalLayout.addWidget(self.linux_button)
        self.android_button = QtWidgets.QPushButton(parent=self.widget)
        self.android_button.setObjectName("android_button")
        self.horizontalLayout.addWidget(self.android_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.inform_label = QtWidgets.QLabel(parent=self.widget)
        self.inform_label.setText("")
        self.inform_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.inform_label.setObjectName("inform_label")
        self.verticalLayout_2.addWidget(self.inform_label)

        self.retranslateUi(programs_download)
        QtCore.QMetaObject.connectSlotsByName(programs_download)

    def retranslateUi(self, programs_download):
        _translate = QtCore.QCoreApplication.translate
        programs_download.setWindowTitle(_translate("programs_download", "Загрузка ПО ИСОД МВД"))
        self.label.setText(_translate("programs_download", "Выберите операционную систему для загрузки"))
        self.windows_button.setText(_translate("programs_download", "Windows"))
        self.linux_button.setText(_translate("programs_download", "Astra Linux"))
        self.android_button.setText(_translate("programs_download", "Android"))
